# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.BlogPosts'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='web_site',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
    ]
